[package]
name = "chess"
version = "0.1.0"
authors = ["Markus Videfors <markus.videfors@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = "0.8.1"
cfg-if = "0.1.10"
